name: Configure AWS Credentials and Deploy
 
on:
  push:
    branches:
      - main
      - master
 
permissions:
  id-token: write  # Allow the workflow to request OIDC tokens
  contents: read   # Allow the workflow to access the repository contents
 
jobs:
  configure-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Latest version as of now
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # Latest version as of now
        with:
          role-to-assume: arn:aws:iam::014498661566:role/saikumar
          role-session-name: github-actions-session
          aws-region: us-east-1
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3  # Latest version as of now
        with:
          terraform_version: 1.9.5  # Latest version as of now
 
      - name: Terraform Init
        run: terraform init
      - name: Terraform apply
        run: terraform apply
 
